### PR TITLE
define "Expert Check: FCFS+"

### LINKED ISSUE #10: Define FCFS+ and Expert Check
Right now, there isn't really text that introduces and explains FCFS+ or "Expert Check".

_Originally posted by @cabo in https://github.com/thomas-fossati/draft-cf-reg-update/issues/5#issuecomment-2489031775_

### PR DESCRIPTION
**Pull request by thomas-fossati**
Fix #10

### CODE REVIEW

**Review by EskoDijk — APPROVED** [review]
Agree to add this. One remaining comment/question is that the current IANA registry policy description is more clear as it spells out "First Come First Served".

In the future a visitor of the registry page will see "FCFS+" and may have no idea what this means. It's not a common abbreviation. So for the final text going into the IANA registry there's possibly a need to spell that out.  In the draft we can of course just use this term, it's properly defined.

**Comment by thomas-fossati** [comment]
> Agree to add this. One remaining comment/question is that the current IANA registry policy description is more clear as it spells out "First Come First Served".

True that.

As a side note, after writing everything down, I'm beginning to think that the difference between "Expert Review (full)" and "Expert Review (Expert Check: FCFS+)," as suggested by @cabo, may not be significant enough to warrant different terms.

All the checks would equally apply to both ranges.  The only difference is that 0-255 requires the DE to judge the potential popularity of the requested C-F in constrained protocols, whilst 10000-64999 doesn't.

Is that worth introducing new semantics?  (Also, would we need to "Update: 8126" if we do that?)

We have a bug in our registration procedures, which has already been abused and can be abused again until we fix it.  If we bundle the fix with the wider IANAbis discussion, we risk delaying an urgent action.

**Comment by cabo** [comment]
We are not updating 8126.
Both policies are Expert Review (Section 4.5) according to 8126.
They differ only in their DE instructions.

Expert Check/FCFS+ only has the well-formedness check; this could be done by machine if the media type registry had an API.
Full Review has the DE looking at the registration and trying to understand it, e.g., if somebody registers a media type parameter set to 800 Hz, they might question whether that should be 8000 Hz instead.

Yes, the difference in DE instructions is somewhat subtle here, but we might have stronger differences later, e.g., in CoAP Option numbers.

**Comment by thomas-fossati** [comment]
If you believe there is no need to update 8126, I trust your (superior) judgment.

Let's run this through IANA (#4) and see if they like the idea.

**Pull request merged**
